### ISSUE TITLE
seqtrimnext -i core crash

### ISSUE THREAD

**Issue by lmanchon** [dariogf/SeqtrimNext#1]
--Hi,

i try to install core database with seqtrimnext -i core
but it failed because it can't find /bank directory.
So, how to install core database using another directory ?

thank you --

**Comment by dariogf** [comment]
Since /bank is not a directory name that is in our code, I suppose you have defined the BLASTDB environment variable to tell STN where to install databases. 

Please, to be sure, use a path like the following (with the formatted subfolder) 

export BLASTDB=/my_path/my_blastdbs/formatted

#create the directories
mkdir -p $BLASTDB

seqtrimnext -i core

**Comment by dariogf** [comment]
If you have any problem with the automatic process (maybe network is locked on your site), you can always download it by hand:

#define location of formatted databases, downloaded databases will be in the parent folder
export BLASTDB=/my_path/my_blastdbs/formatted

#create the directories
mkdir -p $BLASTDB

cd /my_path/my_blastdbs/

wget http://www.scbi.uma.es/downloads/core_db.zip

unzip core_db.zip

#format dbs

seqtrimnext -c

**Comment by lmanchon** [comment]
all right,
it works fine now;

gracias.
