### ISSUE TITLE
Illumina Hiseq 2000 paired-end reads

### ISSUE THREAD

**Issue by lmanchon** [dariogf/SeqtrimNext#2]
--Again me,

is SeqTrimNext able to process paired-end reads relevant to Hiseq 2000/2500 or only
454 platform ?

thank you

**Comment by dariogf** [comment]
Yes, Illumina files are supported, but since they are a lot of sequences you should use a cluster if you want to make a lot of preprocessing on it. 

seqtrimnext -h tells you all the templates available. Use the ones tagged with _short_read for illumina sequences, like this one. 

transcriptomics_short_reads.txt

You can also execute seqtrimnext once and then modify and use the used_params.txt file as a custom template with the plugins and parameters that you want.

Be sure to disable remove_repetitions in the template if you build your own because this option only applies for 454 files.

**Comment by lmanchon** [comment]
okay, good
thanx.
