### ISSUE TITLE
Process time

### ISSUE THREAD

**Issue by JehanneQuentin** [dariogf/SeqtrimNext#3]
Hello,

I'm currently working on RADseq data and I decided to use Seqtrimnext to clean the fastq files. These files are quite big (> 4GB for each) so I'm running the tool with more than 12 cores. Still, it takes so much time to process (> 5 days).

I've noticed that a checkpoint file is created every, I don't know, 200-500 reads cleaned. Is there a way to remove it to decrease the process time? Or maybe I've messed up somewhere or my files are just too big?

Thanks in advance for your support!

Quentin Jehanne

**Comment by dariogf** [comment]
Hi quentin. 

Maybe stn is not properly configured. Have you double cheked that it is using all your CPUs? If you are using a cluster check the load of each node and be sure to specify the comunicación subnet with the -s option. Eg. -s 10.247

A partial ip should be used, it should match the interfaces used for ínter node comunications. 

The checkpoint is not expensive in computational time since it only saves a number. 

You can increase the size of the processing packet with -g option. 

You can also modify the databases and cleaning pipeline using the plugin list parameter in the template file. Maybe you dont need to remove contsminants which is a very expensive phase. 

---

Un saludo, 
Dario

**Comment by JehanneQuentin** [comment]
Thanks for your reply, I'll check that out!
